name: Python Package CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]  # Test on multiple Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install quelib

    - name: Lint with flake8  # Optional linting step
      run: |
        pip install flake8
        flake8 .

    - name: Run tests  # Optional testing step
      run: |
        pip install pytest
        pytest

    - name: Publish to PyPI  # Optional publishing step
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        pip install twine
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://upload.pypi.org/legacy/ dist/* --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
